name: Actions workflow commands

on: [push, pull_request]

jobs:
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: Show list of files
        id: listing
        run: |
          pwd
          ls
      - name: Checkout
        id: checkout
        uses: actions/checkout@v1
      - name: List files after checkout list of files
        id: listing-after-checkout
        run: |
          pwd
          ls      
      - name: simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Nick
      - name: log greeting time
        run: echo "${{ steps.greet.outputs.time }}"